# Generated by Django 4.2.7 on 2023-11-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='type',
            field=models.CharField(choices=[('A', 'Flat Image'), ('B', 'Blue print')], max_length=100, null=True),
        ),
    ]
